# Generated by Django 4.0.3 on 2022-04-26 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='dateentered',
            new_name='date_entered',
        ),
    ]
