# Generated by Django 4.0.3 on 2022-05-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_rename_dateentered_resource_date_entered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingminutes',
            old_name='meetingid',
            new_name='meetingID',
        ),
        migrations.AlterField(
            model_name='meetingminutes',
            name='minutestext',
            field=models.TextField(),
        ),
    ]
